const videos = {
    hero: "/videos/hero_section_2.webm",
    hero2: "/videos/hero_section_1.mp4",
    hero3: "/videos/hero_section_3.mp4",
    hero4: "/videos/hero_section_4.mp4",
    aboutUsTamil: "https://www.youtube.com/embed/FNNnlUTw0Sg",
    aboutUsEnglish: "https://www.youtube.com/embed/Q2z29RzFfkI",
    ourStoryTamil: "https://www.youtube.com/embed/UcyIOAHbpHY",
    ourStoryEnglish: "https://www.youtube.com/embed/02CcY9Z_t_8",
    justForYouPlan_english: "https://www.youtube.com/embed/ldJP2kfCsJg",
    justForTwoPlan_english: "https://www.youtube.com/embed/9_JrOGgY1zQ",
    triMePlan_english: "https://www.youtube.com/embed/Z55rlTMAkEY",
    quadPlan_english: "https://www.youtube.com/embed/Kce0-gTDH00",
    sheroPlan_english: "https://www.youtube.com/embed/Q7hbRYYoaz4",
    quadProPlan_english: "https://www.youtube.com/embed/UGjdjSQiHuo",
    completeWellnessPlan_english: "https://www.youtube.com/embed/V-VEMNjlZsI",
    ultimateWellnessPlan_english: "https://www.youtube.com/embed/m1ur1Vyaeks",
    miniMePlan_english: "https://www.youtube.com/embed/6-pafpdyINA",
    just50Plan_english: "https://www.youtube.com/embed/i7ufoYO-rQI",
    justForYouPlan_tamil: "https://www.youtube.com/embed/ISSdpKBt0ho",
    justForTwoPlan_tamil: "https://www.youtube.com/embed/xjEBrxNKdsU",
    triMePlan_tamil: "https://www.youtube.com/embed/HIvNRbI4uAw",
    quadPlan_tamil: "https://www.youtube.com/embed/5whm82h3Wys",
    sheroPlan_tamil: "https://www.youtube.com/embed/QU8hJXPa3w8",
    quadProPlan_tamil: "https://www.youtube.com/embed/kVLHx8AlJ_Q",
    completeWellnessPlan_tamil: "https://www.youtube.com/embed/SN0bLSsdzRM",
    ultimateWellnessPlan_tamil: "https://www.youtube.com/embed/IqjCVZ6pBxk",
    miniMePlan_tamil: "https://www.youtube.com/embed/FhaeBvROnXc",
    just50Plan_tamil: "https://www.youtube.com/embed/2Vl4wL4UdNo",
    comprehensivePlans_tamil: "https://www.youtube.com/embed/vevAQbiVwqU",
};


export default videos;
